export const carouselData = [
  {
    img: "https://home.drago.pe/attachment/web/home/drago-muy-pronto.webp",
  },
  {
    img: "https://home.drago.pe/attachment/web/home/tienda-de-ropa-drago.webp",
  },
  {
    img: "https://home.drago.pe/attachment/web/enterprise/tenemos-el-mejor-equipo.webp",
  },
  {
    img: "https://home.drago.pe/attachment/web/premium/servicio-premium.webp",
  },
  {
    img: "https://home.drago.pe/attachment/web/home/1-aniversario-drago.webp",
  },
];

export const categoriesData = [
  {
    img: "https://home.drago.pe/attachment/web/home-coleccion/mujer-polo-estampado.webp",
    title: "mujer polo estampado",
    genero: "mujer",
    categoria: "polos-estampados",
  },
  {
    img: "https://home.drago.pe/attachment/web/home-coleccion/mujer-polo-basico.webp",
    title: "mujer polo basico",
    genero: "mujer",
    categoria: "polos-basicos",
  },
  {
    img: "https://home.drago.pe/attachment/web/home-coleccion/hombre-polo-estampado.webp",
    title: "hombre polo estampado",
    genero: "hombre",
    categoria: "polos-estampados",
  },
  {
    img: "https://home.drago.pe/attachment/web/home-coleccion/hombre-polo-basico.webp",
    title: "hombre polo basico",
    genero: "hombre",
    categoria: "polos-basicos",
  },
  {
    img: "https://home.drago.pe/attachment/web/home-coleccion/casaca-acolchada.png",
    title: "unisex casaca acolchada",
    genero: "mujer",
    categoria: "casacas",
  },
  {
    img: "https://home.drago.pe/attachment/web/home-coleccion/mujer-polo-camisero.webp",
    title: "unisex polo camisero",
    genero: "",
    categoria: "",
  },
];

const data = [
  {
    imgs: [
      "0000031/013/1.webp",
      "0000031/013/2.webp",
      "0000031/013/3.webp",
      "0000031/013/4.webp",
    ],
    title: "POLO HOMBRE CUELLO REDONDO DRAGON",
    path: "polo-hombre-cuello-redondo-dragon",
    state: "",
    genero: "hombre",
    categoria: "polos-estampados",
    color: "verde",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000028/006/1.webp",
      "0000028/006/2.webp",
      "0000028/006/3.webp",
      "0000028/006/4.webp",
    ],
    title: "POLO HOMBRE CUELLO REDONDO LEON",
    path: "polo-hombre-cuello-redondo-leon",
    state: "",
    genero: "hombre",
    categoria: "polos-estampados",
    color: "azul",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "20",
  },
  {
    imgs: [
      "0000001/001/1.webp",
      "0000001/001/2.webp",
      "0000001/001/3.webp",
      "0000001/001/5.webp",
    ],
    title: "POLO MUJER CUELLO V DRAGO",
    path: "polo-mujer-cuello-v-rendondo",
    state: "",
    genero: "mujer",
    categoria: "polos-basicos",
    color: "gris",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000001/007/1.webp",
      "0000001/007/2.webp",
      "0000001/007/3.webp",
      "0000001/007/4.webp",
    ],
    title: "POLO MUJER CUELLO V DRAGO",
    path: "polo-mujer-cuello-v-rendondo",
    state: "",
    genero: "mujer",
    categoria: "polos-basicos",
    color: "gris Oscuro",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000013/001/1.webp",
      "0000013/001/3.webp",
      "0000013/001/4.webp",
      "0000013/001/5.webp",
    ],
    title: "POLO MUJER CUELLO REDONDO",
    path: "polo-mujer-cuello-rendondo",
    state: "",
    genero: "mujer",
    categoria: "polos-basicos",
    color: "gris",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: ["0000049/005/1.webp"],
    title: "POLO MUJER CUELLO REDONDO - NAVIDAD",
    path: "polo-mujer-cuello-redondo-navidad",
    state: "",
    genero: "mujer",
    categoria: "polos-estampados",
    color: "negro",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: ["0000043/009/1.webp"],
    title: "POLO MUJER CUELLO V - TIME",
    path: "polo-mujer-cuello-v-time",
    state: "",
    genero: "mujer",
    categoria: "polos-estampados",
    color: "blanco",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "20",
  },
  {
    imgs: ["0000050/001/1.webp"],
    title: "POLO HOMBRE CUELLO REDONDO - NAVIDAD",
    path: "polo-hombre-cuello-redondo-navidad",
    state: "",
    genero: "hombre",
    categoria: "polos-estampados",
    color: "blanco",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000090/004/1.webp",
      "0000090/004/2.webp",
      "0000090/004/3.webp",
    ],
    title: "POLO MUJER CUELLO V - NETFLIX 3",
    path: "polo-mujer-cuello-v",
    state: "",
    genero: "mujer",
    categoria: "polos-estampados",
    color: "celeste",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "20",
  },
  {
    imgs: [
      "0000025/001/3.webp",
      "0000025/001/1.webp",
      "0000025/001/4.webp",
      "0000025/001/5.webp",
    ],
    title: "POLO HOMBRE CUELLO REDONDO",
    path: "polo-hombre-cuello-redondo",
    state: "",
    genero: "hombre",
    categoria: "polos-basicos",
    color: "gris",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "25",
  },
  {
    imgs: [
      "0000025/010/1.webp",
      "0000025/010/3.webp",
      "0000025/010/4.webp",
      "0000025/010/6.webp",
    ],
    title: "POLO HOMBRE CUELLO REDONDO",
    path: "polo-hombre-cuello-redondo",
    state: "",
    genero: "hombre",
    categoria: "polos-basicos",
    color: "vino",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "25",
  },
  {
    imgs: [
      "0000025/006/1.webp",
      "0000025/006/3.webp",
      "0000025/006/4.webp",
      "0000025/006/6.webp",
    ],
    title: "POLO HOMBRE CUELLO REDONDO",
    path: "polo-hombre-cuello-redondo",
    state: "",
    genero: "hombre",
    categoria: "polos-basicos",
    color: "azul noche",
    marca: "drago",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "25",
  },
  {
    imgs: [
      "0000035/014/1.webp",
      "0000035/014/2.webp",
      "0000035/014/4.webp",
      "0000035/014/5.webp",
    ],
    title: "CASACA ACOLCHADA HOMBRE - LÚCUMA",
    path: "casaca-acolchada-hombre",
    state: "",
    genero: "hombre",
    categoria: "casacas",
    color: "lucuma",
    marca: "drago",
    price_unit: "48.99",
    price_real: "69.99",
    stock: "0",
  },
  {
    imgs: [
      "0000040/012/1.webp",
      "0000040/012/2.webp",
      "0000040/012/3.webp",
    ],
    title: "CASACA ACOLCHADA MUJER - ROJO",
    path: "casaca-acolchada-mujer",
    state: "",
    categoria: "casacas",
    genero: "mujer",
    marca: "drago",
    color: "rojo",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "20",
  },
  {
    imgs: [
      "0000039/014/1.webp",
      "0000039/014/3.webp",
      "0000039/014/5.webp",
      "0000039/014/6.webp",
    ],
    title: "CASACA ACOLCHADA MUJER - LUCUMA",
    path: "casaca-acolchada-mujer",
    state: "",
    categoria: "casacas",
    genero: "mujer",
    marca: "drago",
    color: "lucuma",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000007/003/1.webp",
      "0000007/003/3.webp",
      "0000007/003/2.webp",
      "0000007/003/5.webp",
    ],
    title: "BLUSA HINDU MOTITA - MAUVE",
    path: "blusa-hindu-motita-mauve",
    state: "",
    categoria: "blusas",
    genero: "mujer",
    marca: "drago",
    color: "mauve",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000094/012/1.webp",
      "0000094/012/2.webp",
      "0000094/012/3.webp",
    ],
    title: "BLUSA CAMILA",
    path: "blusa-camila",
    state: "New Release",
    categoria: "blusas",
    genero: "mujer",
    marca: "drago",
    color: "rojo",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "20",
  },
  {
    imgs: [
      "0000094/008/1.webp",
      "0000094/008/2.webp",
      "0000094/008/3.webp",
    ],
    title: "BLUSA CAMILA",
    path: "blusa-camila",
    state: "New Release",
    categoria: "blusas",
    genero: "mujer",
    marca: "drago",
    color: "celeste",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "18",
  },
  {
    imgs: [
      "0000094/005/1.webp",
      "0000094/005/2.webp",
    ],
    title: "BLUSA CAMILA",
    path: "blusa-camila",
    state: "New Release",
    categoria: "blusas",
    genero: "mujer",
    marca: "drago",
    color: "negro",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000094/010/1.webp",
      "0000094/010/2.webp",
    ],
    title: "BLUSA CAMILA",
    path: "blusa-camila",
    state: "New Release",
    categoria: "blusas",
    genero: "mujer",
    marca: "drago",
    color: "vino",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
  {
    imgs: [
      "0000093/009/1.webp",
      "0000093/009/2.webp",
      "0000093/009/3.webp",
    ],
    title: "CAPAS",
    path: "capa",
    state: "",
    categoria: "capas",
    genero: "mujer",
    marca: "drago",
    color: "blanco",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "2",
  },
  {
    imgs: [
      "0000093/010/1.webp",
      "0000093/010/2.webp",
      "0000093/010/3.webp",
    ],
    title: "CAPAS",
    path: "capa",
    state: "",
    categoria: "capas",
    genero: "mujer",
    marca: "drago",
    color: "vino",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "15",
  },
  {
    imgs: [
      "0000012/010/1.webp",
      "0000012/010/2.webp",
      "0000012/010/4.webp",
      "0000012/010/5.webp",
    ],
    title: "POLO RIP NACIONAL CUELLO ALTO - VINO",
    path: "polo-rip-nacional-cuello-alto",
    state: "",
    categoria: "polos-rip",
    genero: "mujer",
    marca: "drago",
    color: "vino",
    price_unit: "48.90",
    price_real: "69.90",
    stock: "0",
  },
];

export function getItems() {
  return data;
}

export function getFilter(categoria, genero) {
  return data.find(
    (ca) => (ca.categoria === categoria) & (ca.genero === genero)
  );
}

export function getProduct(path, color) {
  return data.find((ca) => (ca.path === path) & (ca.color === color));
}
